### ISSUE TITLE
pylint-pydantic requires Python >=3.9

### ISSUE THREAD

**Issue by davnat** [fcfangcc/pylint-pydantic#13]
Both Pylint and Pydantic support Python 3.7.2+: would it be possible to use the same requirements in this plugin?

Thank you, cheers.

**Comment by fcfangcc** [comment]
> Both Pylint and Pydantic support Python 3.7.2+: would it be possible to use the same requirements in this plugin?
> 
> Thank you, cheers.

version 0.1.7 is available
