### ISSUE TITLE
Support dataclasses?

### ISSUE THREAD

**Issue by kasbah** [fcfangcc/pylint-pydantic#16]
Hey, thanks for this plugin. I've [added it to our pylint config](
https://gitlab.com/edea-dev/edea/-/blob/d4f5037b2bf01c80cbac6edee16b5c7da44304f6/.pylintrc#L88-90) but it doesn't seem to do much because we use `@pydantic.dataclasses.dataclass` instead of `BaseModel`. I'm guessing it doesn't support it yet? Is support for dataclasses planned? 

Specifically it doesn't seem to handle `@validator`  "bad-classmethod-argument" and also doesn't override "too-many-arguments".

**Comment by fcfangcc** [comment]
After my testing, it can be supported. Can you give me doesn't support example model


```python
@pydantic.dataclasses.dataclass
class TestDataclass:
    a: int = 10

    @property
    def test(self):
        return f"{self.a+10}"

    @validator("a")
    def valid_after(cls, value):
        return value

    @validator("a", pre=True)
    def valid_pre(cls, value):
        return value

    @root_validator
    def valid_root_after(cls, values):
        return values

    @root_validator(pre=True)
    def valid_root_pre(cls, values):
        return values

    @pydantic.root_validator
    def valid_pydantic_qualname(cls, values):
        return values

    @pydantic.root_validator(pre=True)
    def valid_pydantic_qualname_pre(cls, values):
        return values

    @root_validator
    def valid_static_method(cls, values):
        values[cls.__name__] = cls.__name__
        return values
```

**Comment by kasbah** [comment]
Thanks so much for checking. I believe you are right, I just tried to reproduce the false positives I thought I saw before and they seem to be gone.
