### ISSUE TITLE
The model_validator decorator can now decorate both class and instance methods

### ISSUE THREAD

**Issue by lmrlyv** [fcfangcc/pylint-pydantic#22]
## Problem description

In the latest release of Pydantic (2023-07-15), the `model_validator` decorator is changed to act differently depending on the `mode` argument. If the argument takes value **_before_**, then it acts like a _classmethod_ where the decorated method takes `cls`. However, if **_after_** is passed to the argument, then the decorated method is an instance method. The problem is that pylint emits **bad-classmethod-argument** error for the latter too.

## Steps to reproduce the problem

```python
class UserModel(BaseModel):
    username: str
    password1: str
    password2: str

    @model_validator(mode='before')
    def check_card_number_omitted(cls, data):
        assert 'card_number' not in data, 'card_number should not be included'
        return data

    @model_validator(mode='after')
    def check_passwords_match(self) -> 'UserModel':  # PYLINT ERROR: bad-classmethod-argument
        pw1 = self.password1
        pw2 = self.password2
        if pw1 is not None and pw2 is not None and pw1 != pw2:
            raise ValueError('passwords do not match')
        return self
```

## Specifications like the version of the project, operating system, or hardware
* pylint version: latest
* pydatic version: 2.0.3
* python version: 3.10
* pylint-pydantic version: 0.2.1

**Comment by fcfangcc** [comment]
Because pylint-pydantic change model_validator to classmethod, ignore **mode** argument. 😅  I will fix it.

**Comment by lmrlyv** [comment]
Yes, sorry for that. The timing of the previous issue which I opened to make it classmethod was so bad. After like one day, pydantic team updated its behavior.

Thanks for actively maintaining this plugin. It's so useful :)

**Comment by lmrlyv** [comment]
I can confirm that your fix solved the issue. Thank you very much, @fcfangcc
