### ISSUE TITLE
Pylint v3.0.0 released, this plugin appears to work with it.

### ISSUE THREAD

**Issue by grigi** [fcfangcc/pylint-pydantic#27]
## Problem description
Pylint v3.0.0 released, this plugin limits pylint dependency to `pylint<3.0,>2.0`.
When overriding it locally, it appears to work just fine however.

## Steps to reproduce the problem

Use `pylint==3.0.0`

**Comment by dtczest** [comment]
I don't think it works, I'm getting this error:
Command line or configuration file:1:0: E0013: Plugin 'pylint_pydantic' is impossible to load, is it installed ? ('No module named 'astroid.node_classes'') (bad-plugin-value)

**Comment by fcfangcc** [comment]
I will try it in spare time
