### ISSUE TITLE
E0611: No name 'AnyUrl' in module 'pydantic' (no-name-in-module)

### ISSUE THREAD

**Issue by Maillol** [fcfangcc/pylint-pydantic#3]
This line:

`from pydantic import AnyUrl, BaseSettings, Field, validator `

produce a false positive pylint error E0611

**Comment by fcfangcc** [comment]
Add `--extension-pkg-whitelist='pydantic'` parameter
[`#1961](https://github.com/samuelcolvin/pydantic/issues/1961)
