### ISSUE TITLE
Support for `pydantic` v1 packaged inside v2

### ISSUE THREAD

**Issue by inikolaev** [fcfangcc/pylint-pydantic#35]
## Problem description

I've updated project to use `pydantic` v2 dependency, but due to a big number of models I still need to use v1 version which is packaged inside and is accessible with `pydantic.v1` import, but the plugin does not recognised namespaced version [here](https://github.com/fcfangcc/pylint-pydantic/blob/main/pylint_pydantic/field.py#L9).

## Steps to reproduce the problem

```python
from pydantic.v1 import BaseModel, Field


class MyModel(BaseModel):
    items: list[int] = Field(...)
    value: str = Field(...)

    @property
    def get(self) -> str:
        return self.value[0:2]


model = MyModel(items=[1, 2, 3, 4, 5], value="test")
items = [i * i for i in model.items]
print(items)
```

Output:

```
pylint mymodel.py 
************* Module mymodel
mymodel.py:10:15: E1136: Value 'self.value' is unsubscriptable (unsubscriptable-object)
mymodel.py:14:24: E1133: Non-iterable value model.items is used in an iterating context (not-an-iterable)
```

If I change `PYDANTIC_FIELD_MODULE` in the plugin to

```python
PYDANTIC_FIELD_MODULE = {"pydantic.fields", "pydantic.v1.fields"}
```

then all errors are gone

## Specifications like the version of the project, operating system, or hardware
* pylint version: 3.1.0
* pydantic version: 2.9.2 
* python version: 3.12.0
* pylint-pydantic version: 0.3.2

**Comment by fcfangcc** [comment]
@inikolaev v0.3.4 fixed this
